[project]
name = "websearchai-flet"
version = "26.1.13"
description = ""
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "DrinkingPants74", email = "DrinkingPants74ose@gmail.com" }
]
dependencies = [
  "flet",
  "httpx",
  "beautifulsoup4",
  "pypng",
  "readability-lxml",
  "numpy",
  "openai",
]

[dependency-groups]
dev = [
  "flet[all]",
]

[tool.flet]
org = "DrinkingPants74"
product = "websearchai"
company = "DrinkingPants74"
copyright = "GPL3.0"

[tool.flet.app]
module = "main.py"
path = "src"
