[project]
name = "websearchai-flet"
version = "26.1.13"
description = ""
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "DrinkingPants74", email = "DrinkingPants74ose@gmail.com" }
]
dependencies = [
  "flet>=0.80.1",
  "httpx==0.28.1",
  "beautifulsoup4==4.14.3",
  "pypng==0.20220715.0",
  "readability-lxml==0.8.4.1",
  "numpy==2.4.1",
  "openai==2.15.0",
]

[dependency-groups]
dev = [
  "flet[all]>=0.80.1",
]

[tool.flet]
org = "DrinkingPants74"
product = "websearchai"
company = "DrinkingPants74"
copyright = "GPL3.0"

[tool.flet.app]
path = "src"
