import flet as ft
import Settings

# Themes for Users to Select From

default = {
    "Dark": {
        "Background": "#1c1c1c",
        "Text": "#CDCDCD",
        "Icon": "#CDCDCD",
        "NavBarIndicator": "",
        "SearchOn": "#00FF00",
        "SearchOff": "#FF0000",
        "UserInputCursor": "#CDCDCD",
        "UserInputBorder": "#CDCDCD",
        "UserInputBorderFocus": "#CDCDCD",
        "UserInputText": "#CDCDCD",
        "UserInputBackground": "#000000",
        "SubmitIcon": "#00AAFF",
        "SettingsLabel": "#CDCDCD",
        "SettingsSliderActive": "#CDCDCD",
        "SettingsSliderInactive": "#000000",
        "ContainerBorderColor": "#CDCDCD",
        "SettingsTabDivider": "#CDCDCD",
        "SettingsTabLabelSelected": "#CDCDCD",
        "SettingsTabLabelUnselected": "#CDCDCD",
        "SettingsTabIndicator": "#1C1C1C",
        "SettingsTabOverlay": "#44000000",
        "ChatButtonBackground": "#000000",

        # MD Sheet Values
        "a_text": "#00AAFF",
        "block_quote_text": "",
        "block_quote_background": "#EFEFEF",
        "checkbox_text": "",
        "code_text": "",
        "del_text": "#cdcdcd",
        "em_text": "#cdcdcd",
        "h1_text": "#cdcdcd",
        "h2_text": "#cdcdcd",
        "h3_text": "#cdcdcd",
        "h4_text": "#cdcdcd",
        "h5_text": "#cdcdcd",
        "h6_text": "#cdcdcd",
        "img_text": "#cdcdcd",
        "list_bullet_text": "#cdcdcd",
        "p_text": "#cdcdcd",
        "strong_text": "#cdcdcd",
        "table_body_text": "#cdcdcd",
        "table_head_text": "#cdcdcd",
    },
    "Light": {
        "Background": "#CDCDCD",
        "Text": "#1C1C1C",
        "Icon": "#1C1C1C",
        "NavBarIndicator": "",
        "SearchOn": "#00FF00",
        "SearchOff": "#FF0000",
        "UserInputCursor": "#1C1C1C",
        "UserInputBorder": "#1C1C1C",
        "UserInputBorderFocus": "#1C1C1C",
        "UserInputText": "#1C1C1C",
        "UserInputBackground": "#FFFFFF",
        "SubmitIcon": "#00AAFF",
        "SettingsLabel": "#1C1C1C",
        "SettingsSliderActive": "#1C1C1C",
        "SettingsSliderInactive": "#FFFFFF",
        "ContainerBorderColor": "#1C1C1C",
        "SettingsTabDivider": "#1C1C1C",
        "SettingsTabLabelSelected": "#1C1C1C",
        "SettingsTabLabelUnselected": "#1C1C1C",
        "SettingsTabIndicator": "#CDCDCD",
        "SettingsTabOverlay": "#44FFFFFF",
        "ChatButtonBackground": "#FFFFFF",

        # MD Sheet Values
        "a_text": "#00AAFF",
        "block_quote_text": "",
        "block_quote_background": "#EFEFEF",
        "checkbox_text": "",
        "code_text": "",
        "del_text": "#1C1C1C",
        "em_text": "#1C1C1C",
        "h1_text": "#1C1C1C",
        "h2_text": "#1C1C1C",
        "h3_text": "#1C1C1C",
        "h4_text": "#1C1C1C",
        "h5_text": "#1C1C1C",
        "h6_text": "#1C1C1C",
        "img_text": "#1C1C1C",
        "list_bullet_text": "#1C1C1C",
        "p_text": "#1C1C1C",
        "strong_text": "#1C1C1C",
        "table_body_text": "#1C1C1C",
        "table_head_text": "#1C1C1C",
    },
}

midnight = {
    "Dark": {
        "Background": "#01497c",
        "Text": "#a9d6e5",
        "Icon": "#a9d6e5",
        "NavBarIndicator": "",
        "SearchOn": "#00FF00",
        "SearchOff": "#FF0000",
        "UserInputCursor": "#a9d6e5",
        "UserInputBorder": "#a9d6e5",
        "UserInputBorderFocus": "#a9d6e5",
        "UserInputText": "#a9d6e5",
        "UserInputBackground": "#012a4a",
        "SubmitIcon": "#00AAFF",
        "SettingsLabel": "#a9d6e5",
        "SettingsSliderActive": "#a9d6e5",
        "SettingsSliderInactive": "#012a4a",
        "ContainerBorderColor": "#a9d6e5",
        "SettingsTabDivider": "#a9d6e5",
        "SettingsTabLabelSelected": "#a9d6e5",
        "SettingsTabLabelUnselected": "#a9d6e5",
        "SettingsTabIndicator": "#01497c",
        "SettingsTabOverlay": "#44012a4a",
        "ChatButtonBackground": "#012a4a",

        # MD Sheet Values
        "a_text": "#00AAFF",
        "block_quote_text": "",
        "block_quote_background": "#EFEFEF",
        "checkbox_text": "",
        "code_text": "",
        "del_text": "#a9d6e5",
        "em_text": "#a9d6e5",
        "h1_text": "#a9d6e5",
        "h2_text": "#a9d6e5",
        "h3_text": "#a9d6e5",
        "h4_text": "#a9d6e5",
        "h5_text": "#a9d6e5",
        "h6_text": "#a9d6e5",
        "img_text": "#a9d6e5",
        "list_bullet_text": "#a9d6e5",
        "p_text": "#a9d6e5",
        "strong_text": "#a9d6e5",
        "table_body_text": "#a9d6e5",
        "table_head_text": "#a9d6e5",
    },
    "Light": {
        "Background": "#89c2d9",
        "Text": "#013a63",
        "Icon": "#013a63",
        "NavBarIndicator": "",
        "SearchOn": "#00FF00",
        "SearchOff": "#FF0000",
        "UserInputCursor": "#013a63",
        "UserInputBorder": "#013a63",
        "UserInputBorderFocus": "#013a63",
        "UserInputText": "#013a63",
        "UserInputBackground": "#a9d6e5",
        "SubmitIcon": "#00AAFF",
        "SettingsLabel": "#013a63",
        "SettingsSliderActive": "#013a63",
        "SettingsSliderInactive": "#a9d6e5",
        "ContainerBorderColor": "#013a63",
        "SettingsTabDivider": "#013a63",
        "SettingsTabLabelSelected": "#013a63",
        "SettingsTabLabelUnselected": "#013a63",
        "SettingsTabIndicator": "#89c2d9",
        "SettingsTabOverlay": "#44a9d6e5",
        "ChatButtonBackground": "#a9d6e5",

        # MD Sheet Values
        "a_text": "#00AAFF",
        "block_quote_text": "#00ff00",
        "block_quote_background": "#FF0000",
        "checkbox_text": "",
        "code_text": "#013a63",
        "code_background": "#a9d6e5",
        "del_text": "#013a63",
        "em_text": "#013a63",
        "h1_text": "#013a63",
        "h2_text": "#013a63",
        "h3_text": "#013a63",
        "h4_text": "#013a63",
        "h5_text": "#013a63",
        "h6_text": "#013a63",
        "img_text": "#013a63",
        "list_bullet_text": "#013a63",
        "p_text": "#013a63",
        "strong_text": "#013a63",
        "table_body_text": "#013a63",
        "table_head_text": "#013a63",
    },
}

amber = {
    "Dark": {
        "Background": "#1c1c1c",
        "Text": "#FFC107",
        "Icon": "#FFC107",
        "NavBarIndicator": "",
        "SearchOn": "#00FF00",
        "SearchOff": "#FF0000",
        "UserInputCursor": "#FFC107",
        "UserInputBorder": "#FFC107",
        "UserInputBorderFocus": "#FFC107",
        "UserInputText": "#FFC107",
        "UserInputBackground": "#000000",
        "SubmitIcon": "#00AAFF",
        "SettingsLabel": "#FFC107",
        "SettingsSliderActive": "#FFC107",
        "SettingsSliderInactive": "#000000",
        "ContainerBorderColor": "#FFC107",
        "SettingsTabDivider": "#FFC107",
        "SettingsTabLabelSelected": "#FFC107",
        "SettingsTabLabelUnselected": "#FFC107",
        "SettingsTabIndicator": "#1C1C1C",
        "SettingsTabOverlay": "#44000000",
        "ChatButtonBackground": "#000000",

        # MD Sheet Values
        "a_text": "#00AAFF",
        "block_quote_text": "",
        "block_quote_background": "#EFEFEF",
        "checkbox_text": "",
        "code_text": "",
        "del_text": "#FFC107",
        "em_text": "#FFC107",
        "h1_text": "#FFC107",
        "h2_text": "#FFC107",
        "h3_text": "#FFC107",
        "h4_text": "#FFC107",
        "h5_text": "#FFC107",
        "h6_text": "#FFC107",
        "img_text": "#FFC107",
        "list_bullet_text": "#FFC107",
        "p_text": "#FFC107",
        "strong_text": "#FFC107",
        "table_body_text": "#FFC107",
        "table_head_text": "#FFC107",
    },
    "Light": {
        "Background": "#CDCDCD",
        "Text": "#AB7300",
        "Icon": "#AB7300",
        "NavBarIndicator": "",
        "SearchOn": "#00FF00",
        "SearchOff": "#FF0000",
        "UserInputCursor": "#AB7300",
        "UserInputBorder": "#AB7300",
        "UserInputBorderFocus": "#AB7300",
        "UserInputText": "#AB7300",
        "UserInputBackground": "#FFFFFF",
        "SubmitIcon": "#00AAFF",
        "SettingsLabel": "#AB7300",
        "SettingsSliderActive": "#AB7300",
        "SettingsSliderInactive": "#FFFFFF",
        "ContainerBorderColor": "#AB7300",
        "SettingsTabDivider": "#AB7300",
        "SettingsTabLabelSelected": "#AB7300",
        "SettingsTabLabelUnselected": "#AB7300",
        "SettingsTabIndicator": "#CDCDCD",
        "SettingsTabOverlay": "#44FFFFFF",
        "ChatButtonBackground": "#FFFFFF",

        # MD Sheet Values
        "a_text": "#00AAFF",
        "block_quote_text": "",
        "block_quote_background": "#EFEFEF",
        "checkbox_text": "",
        "code_text": "",
        "del_text": "#AB7300",
        "em_text": "#AB7300",
        "h1_text": "#AB7300",
        "h2_text": "#AB7300",
        "h3_text": "#AB7300",
        "h4_text": "#AB7300",
        "h5_text": "#AB7300",
        "h6_text": "#AB7300",
        "img_text": "#AB7300",
        "list_bullet_text": "#AB7300",
        "p_text": "#AB7300",
        "strong_text": "#AB7300",
        "table_body_text": "#AB7300",
        "table_head_text": "#AB7300",
    },
}


list = { "Default": default, "Midnight": midnight}#, "Amber": amber }


def get_markdown_sheet():
    return ft.MarkdownStyleSheet(
        a_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["a_text"], size=16),
        p_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["Text"], size=16),
        strong_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["Text"], size=16),
        h1_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["h1_text"], size=48),
        h2_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["h2_text"], size=32),
        h3_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["h3_text"], size=24),
        h4_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["h4_text"], size=20),
        h5_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["h5_text"], size=20),
        h6_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["h6_text"], size=16),
        list_bullet_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["Text"], size=16),
        blockquote_text_style=ft.TextStyle(bgcolor=Settings.userTheme[Settings.theme]["block_quote_background"], color=Settings.userTheme[Settings.theme]["block_quote_text"]),
        code_text_style=ft.TextStyle(color=Settings.userTheme[Settings.theme]["Text"], size=16),
        codeblock_decoration=ft.BoxDecoration(bgcolor=Settings.userTheme[Settings.theme]["block_quote_background"])
    )

def get_markdown_codeTheme():
    return ft.MarkdownCustomCodeTheme(
    addition=ft.TextStyle(),
    attr=ft.TextStyle(),
    attribute=ft.TextStyle(),
    built_in=ft.TextStyle(color="#FF0000"),
    builtin_name=ft.TextStyle(color="#00ff00"),
    bullet=ft.TextStyle(),
    class_name=ft.TextStyle(),
    code=ft.TextStyle(color="#0000ff"),
    comment=ft.TextStyle(),
    deletion=ft.TextStyle(),
    doctag=ft.TextStyle(),
    emphasis=ft.TextStyle(),
    formula=ft.TextStyle(),
    function=ft.TextStyle(),
    keyword=ft.TextStyle(),
    link=ft.TextStyle(),
    link_label=ft.TextStyle(),
    literal=ft.TextStyle(),
    meta=ft.TextStyle(),
    meta_keyword=ft.TextStyle(),
    meta_string=ft.TextStyle(),
    name=ft.TextStyle(),
    number=ft.TextStyle(),
    operator=ft.TextStyle(),
    params=ft.TextStyle(),
    pattern_match=ft.TextStyle(),
    quote=ft.TextStyle(),
    regexp=ft.TextStyle(),
    root=ft.TextStyle(),
    section=ft.TextStyle(),
    selector_attr=ft.TextStyle(),
    selector_class=ft.TextStyle(),
    selector_id=ft.TextStyle(),
    selector_pseudo=ft.TextStyle(),
    selector_tag=ft.TextStyle(),
    string=ft.TextStyle(),
    strong=ft.TextStyle(),
    stronge=ft.TextStyle(),
    subst=ft.TextStyle(),
    subtr=ft.TextStyle(),
    symbol=ft.TextStyle(),
    tag=ft.TextStyle(),
    template_tag=ft.TextStyle(),
    template_variable=ft.TextStyle(),
    title=ft.TextStyle(),
    type=ft.TextStyle(),
    variable=ft.TextStyle(),
    )

def get_markdown_codeSheet():
    return ft.MarkdownStyleSheet(
        # code_text_style=ft.TextStyle(bgcolor=Settings.userTheme[Settings.theme]["code_background"], color=Settings.userTheme[Settings.theme]["Text"], size=16),
        codeblock_decoration=ft.BoxDecoration(bgcolor="#ff0000", shape=ft.BoxShape.CIRCLE)#, image=None, border=None, shadows=None,)
    )
