name: Build Whisper.cpp Binaries

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of each month at midnight
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build-whisperCPP-binaries:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: MacOS

          - os: ubuntu-latest
            platform: Linux

          - os: windows-latest
            platform: Window


    runs-on: ${{ matrix.os }}
    name: Build Binaries - ${{ platform }}

    steps:
      - name: Install SDL2 (MacOS)
        if: contains(matrix.os, macos-latest)
        run: |
          brew install sdl2

      - name: Install SDL2 (Linux)
        if: contains(matrix.os, ubuntu-latest)
        run: |
          sudo apt-get install libsdl2-dev

      - name: Clone and Build Whisper.cpp
        id: clone
        run: |
          git clone https://github.com/ggml-org/whisper.cpp.git
          cd whisper.cpp
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
          cmake -B build -DWHISPER_SDL2=ON
          cmake --build build --config Release -j
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Download Model
        run: |
          cd ./whisper.cpp/build/bin/
          sh ./models/download-ggml-model.sh base.en
          mv ggml-base.en.bin ./build/bin

      - name: Create Zip
        run: |
          cd ./whisper.cpp/build/bin/
          cp LICENSE ./build/bin/



      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.app_name }}
          path: whisper.cpp/whisper-${{ steps.clone.outputs.tag }}-${{ matrix.platform }}.zip
          retention-days: 90

      - name: Create Release
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: whisper-${{ steps.clone.outputs.tag }}
          name: whisper.cpp ${{ steps.clone.outputs.tag }}
          files: whisper.cpp/whisper-${{ steps.clone.outputs.tag }}-bin-linux-cuda-x64.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
